version: '3.8'

services:
  flask_cicd:
    image: flask_cicd:latest
    container_name: flask_cicd
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    ports:
      - "5000:5000"